# Generated by Django 3.2.4 on 2021-11-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0002_alter_rating_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookShop.author', verbose_name='Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookShop.genre', verbose_name='Genre'),
        ),
    ]
