# Generated by Django 3.2.7 on 2021-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0005_auto_20211109_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='credit',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='credit_currency',
            new_name='money_currency',
        ),
    ]
