# Generated by Django 3.2.4 on 2021-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0010_alter_cartproduct_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9, verbose_name='Total price'),
        ),
    ]
