# Generated by Django 3.2.4 on 2021-11-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0011_alter_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Title'), unique=True),
        ),
    ]
