# Generated by Django 3.2.4 on 2021-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0013_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Title'), unique=True),
        ),
    ]
