# Generated by Django 3.2.4 on 2021-12-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bookShop', '0018_alter_cartproduct_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
