# Generated by Django 3.2.4 on 2021-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0021_auto_20211201_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='Def_title', max_length=150, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='title',
            field=models.CharField(default='Def_title', max_length=150, verbose_name='Title'),
        ),
    ]
