# Generated by Django 3.2.4 on 2021-12-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0022_auto_20211202_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_price_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='money',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='money_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='bookShop.Book'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
