# Generated by Django 3.2.4 on 2021-12-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0024_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='bookShop.CartProduct'),
        ),
    ]
