# Generated by Django 3.2.4 on 2021-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0026_auto_20211202_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount_of_products',
            field=models.IntegerField(default=0),
        ),
    ]
