# Generated by Django 3.2.4 on 2021-12-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0027_cart_total_amount_of_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersCart', to='bookShop.customer'),
        ),
    ]
