# Generated by Django 3.2.4 on 2021-12-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0029_auto_20211208_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
