# Generated by Django 3.2.4 on 2021-12-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0032_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
